version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demo.com
      PGADMIN_DEFAULT_PASSWORD: Password123
    ports:
      - "8080:80"
    
  FlaskApp:
    image: python:v6
    container_name: flaskapp_container
    environment:
      DB_NAME: userdb
      DB_USER: postgres
      DB_PASSWORD: Password123
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "5000:5000"
